### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by twyatt** [JuulLabs/tuulbox#48]
```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <redacted>, PID: 2511
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: androidx.startup.StartupException: java.lang.VerifyError: Verifier rejected class com.juul.tuulbox.logging.Log: void com.juul.tuulbox.logging.Log.setTagGenerator(com.juul.tuulbox.logging.TagGenerator) failed to verify: void com.juul.tuulbox.logging.Log.setTagGenerator(com.juul.tuulbox.logging.TagGenerator): [0x7] cannot access instance field java.lang.Object com.juul.tuulbox.logging.LogAtomicTagGeneratorRefVolatile.atomicTagGenerator from object of type Reference: com.juul.tuulbox.logging.TagGenerator (declaration of 'com.juul.tuulbox.logging.Log' appears in /data/app/~~2lXJVJlT4RzrInS6IeQoog==/<redacted>-rncQLm21NtZWWOeKAmlI8w==/base.apk!classes5.dex)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7247)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6783)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6700)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: androidx.startup.StartupException: androidx.startup.StartupException: java.lang.VerifyError: Verifier rejected class com.juul.tuulbox.logging.Log: void com.juul.tuulbox.logging.Log.setTagGenerator(com.juul.tuulbox.logging.TagGenerator) failed to verify: void com.juul.tuulbox.logging.Log.setTagGenerator(com.juul.tuulbox.logging.TagGenerator): [0x7] cannot access instance field java.lang.Object com.juul.tuulbox.logging.LogAtomicTagGeneratorRefVolatile.atomicTagGenerator from object of type Reference: com.juul.tuulbox.logging.TagGenerator (declaration of 'com.juul.tuulbox.logging.Log' appears in /data/app/~~2lXJVJlT4RzrInS6IeQoog==/<redacted>-rncQLm21NtZWWOeKAmlI8w==/base.apk!classes5.dex)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:162)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7242)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6783) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6700) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: androidx.startup.StartupException: java.lang.VerifyError: Verifier rejected class com.juul.tuulbox.logging.Log: void com.juul.tuulbox.logging.Log.setTagGenerator(com.juul.tuulbox.logging.TagGenerator) failed to verify: void com.juul.tuulbox.logging.Log.setTagGenerator(com.juul.tuulbox.logging.TagGenerator): [0x7] cannot access instance field java.lang.Object com.juul.tuulbox.logging.LogAtomicTagGeneratorRefVolatile.atomicTagGenerator from object of type Reference: com.juul.tuulbox.logging.TagGenerator (declaration of 'com.juul.tuulbox.logging.Log' appears in /data/app/~~2lXJVJlT4RzrInS6IeQoog==/<redacted>-rncQLm21NtZWWOeKAmlI8w==/base.apk!classes5.dex)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:162)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:148)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7242) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6783) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6700) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-03-16 11:21:12.846 2511-2511/<redacted> E/AndroidRuntime: Caused by: java.lang.VerifyError: Verifier rejected class com.juul.tuulbox.logging.Log: void com.juul.tuulbox.logging.Log.setTagGenerator(com.juul.tuulbox.logging.TagGenerator) failed to verify: void com.juul.tuulbox.logging.Log.setTagGenerator(com.juul.tuulbox.logging.TagGenerator): [0x7] cannot access instance field java.lang.Object com.juul.tuulbox.logging.LogAtomicTagGeneratorRefVolatile.atomicTagGenerator from object of type Reference: com.juul.tuulbox.logging.TagGenerator (declaration of 'com.juul.tuulbox.logging.Log' appears in /data/app/~~2lXJVJlT4RzrInS6IeQoog==/<redacted>-rncQLm21NtZWWOeKAmlI8w==/base.apk!classes5.dex)
        at com.example.app.init.TimberInitializer.create(TimberInitializer.kt:26)
        at com.example.app.init.TimberInitializer.create(TimberInitializer.kt:16)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
            ... 16 more
```

**Comment by twyatt** [comment]
Was caused by app using 0.15.x of atomicfu with a version of Tuulbox (pre-3.1.1 — which used atomicfu 0.14.x).
Bumping Tuulbox version in app to 3.2.0 (which uses atomicfu 0.15.1) fixed the issue.
